global using BLL.Entities;
global using BLL.Interfaces;
global using BLL.Services;
global using DAL.Entities;
global using DAL.Interfaces;
global using DAL.Services;
global using Microsoft.AspNetCore.Mvc;
global using System.Text;
global using TFTIC_BackEnd_VetClinic_Web_API.Tools;
